alias config='/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME'
abbr --add v 'nvim'
abbr --add copm 'config push origin master'
abbr --add cc 'config checkout'
abbr --add cs 'config status'
abbr --add ca 'config add'
abbr --add ccm 'config commit -m "'
